# Generated by Django 5.2.8 on 2025-11-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releaving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releavingletter',
            name='letter_file',
            field=models.FileField(blank=True, null=True, upload_to='releaving_letters/'),
        ),
        migrations.AddField(
            model_name='releavingletter',
            name='placed_in_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
