# Generated by Django 5.2.8 on 2025-11-22 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_employee_code'),
        ('releaving', '0002_releavingletter_letter_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releavingletter',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releaving_letters', to='employees.employee'),
        ),
    ]
