# Generated by Django 5.2.8 on 2025-11-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_employee_code'),
        ('payslips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'verbose_name': 'Payslip', 'verbose_name_plural': 'Payslips'},
        ),
        migrations.AddField(
            model_name='payslip',
            name='payslip_file',
            field=models.FileField(blank=True, help_text='Generated payslip document', null=True, upload_to='payslips/'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('employee', 'month_year')},
        ),
    ]
