# Generated by Django 5.2.8 on 2025-11-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikeLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hike_start_date', models.DateField()),
                ('employee_code', models.CharField(max_length=20)),
                ('old_package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hike_letter_file', models.FileField(blank=True, null=True, upload_to='hike_letters/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hike_letters', to='employees.employee')),
            ],
        ),
    ]
