# Generated by Django 5.2.8 on 2025-11-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='offer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
