# Generated by Django 5.2.8 on 2025-11-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerletters', '0002_offerletter_offer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='series_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
