# Generated by Django 5.2.8 on 2025-11-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerletters', '0003_offerletter_employee_code_offerletter_series_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='variable_pay_per_annum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Optional Variable Pay (Annual) from offer letter', max_digits=14, null=True),
        ),
    ]
